name: Daily Script

on:
  push:
  pull_request:
  schedule:
    - cron: '0 08,20 * * *'

# 设置时区
env:
  TZ: Asia/Shanghai

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run daily script
      env:
          COOKIE: ${{ secrets.COOKIE }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
      run: sh ./daily_script.sh
